kind: pipeline
type: exec
name: default

steps:
- name: build
  commands: 
  - docker build -t expenses/api .

- name: publish
  image: plugins/docker
  settings:
    repo: registry.koda.ws/expenses/api
    registry: registry.koda.ws
    username: testuser
    password: testpassword
