kind: pipeline
type: docker
name: default

steps:
- name: build
  image: ruby:2.6
  commands:
  - apt-get update -qq && apt-get install -y nodejs postgresql-client
  - gem install bundler:2.0.2
  - bundle install

- name: publish
  image: plugins/docker
  settings:
    repo: registry.koda.ws/expenses/api
    registry: registry.koda.ws
    username: testuser
    password: testpassword
